theme: jekyll-theme-slate

title: Jack Lubin

description: Postdoctoral researcher in Astrophysics at the University of California, Los Angeles &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
